### ISSUE TITLE
NPE in Log4jv2Logger.getLevel

### ISSUE THREAD

**Issue by j3rem1e** [ops4j/org.ops4j.pax.logging#408]
This issue appears randomly in Karaf 4.3.2 when using the shell command "log:display" : 

```
java.lang.NullPointerException: null
        at org.ops4j.pax.logging.log4jv2.Log4jv2Logger.getLevel(Log4jv2Logger.java:196) ~[bundleFile:?]
        at org.ops4j.pax.logging.log4jv2.Log4jv2Logger.isEnabled(Log4jv2Logger.java:97) ~[bundleFile:?]
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1898) [bundleFile:?]
        at org.apache.logging.log4j.spi.AbstractLogger.trace(AbstractLogger.java:2469) [bundleFile:?]
        at org.elasticsearch.cluster.NodeConnectionsService.connectDisconnectedTargets(NodeConnectionsService.java:197) ~[elasticsearch-7.8.0.jar:7.8.0]
```

It's caused by this line : https://github.com/ops4j/org.ops4j.pax.logging/blob/main/pax-logging-log4j2/src/main/java/org/ops4j/pax/logging/log4j2/internal/PaxLoggerImpl.java#L1057

If a logger is OFF, then PaxLoggerImpl.getLogLevel() returns null : the switch case in Log4jv2Logger.getLevel fails with a NPE.

As a logger shouldn't throw, the exception is not catched an the thread stops.

**Comment by j3rem1e** [comment]
thank you !

**Comment by jbonofre** [comment]
See https://issues.apache.org/jira/browse/KARAF-7262 I have couple of improvements to do on Pax Logging regarding R8 support, so I will cut the release and upgrade in Karaf.
