### ISSUE TITLE
Build broken on Java 17

### ISSUE THREAD

**Issue by oliverlietz** [ops4j/org.ops4j.pax.logging#439]
Example:
```
[INFO] Running org.ops4j.pax.logging.it.AllLoggingFacadesIntegrationTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.7 s <<< FAILURE! - in org.ops4j.pax.logging.it.AllLoggingFacadesIntegrationTest
[ERROR] org.ops4j.pax.logging.it.AllLoggingFacadesIntegrationTest  Time elapsed: 0.693 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1436)
	at java.base/java.net.URL.<init>(URL.java:680)
	at org.apache.felix.framework.util.SecureAction.createURL(SecureAction.java:256)
	at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:148)
	at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:76)
	at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:799)
	at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:480)
	at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:148)
	at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:462)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3227)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:120)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:340)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:209)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:457)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @2f3d6cd8
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:104)
	... 28 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @2f3d6cd8
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:871)
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:79)
	... 28 more
```
Failing ITs:

```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AllLoggingFacadesIntegrationTest.org.ops4j.pax.logging.it.AllLoggingFacadesIntegrationTest » ExceptionInInitializer
[ERROR]   CleanIntegrationTest.org.ops4j.pax.logging.it.CleanIntegrationTest » ExceptionInInitializer
[ERROR]   DefaultLogIntegrationTest.org.ops4j.pax.logging.it.DefaultLogIntegrationTest » ExceptionInInitializer
[ERROR]   DefaultLogThresholdIntegrationTest.org.ops4j.pax.logging.it.DefaultLogThresholdIntegrationTest » ExceptionInInitializer
[ERROR]   DefaultLogToFileSingletonIntegrationTest.org.ops4j.pax.logging.it.DefaultLogToFileSingletonIntegrationTest » ExceptionInInitializer
[ERROR]   EventAdminIntegrationTest.org.ops4j.pax.logging.it.EventAdminIntegrationTest » ExceptionInInitializer
[ERROR]   H2SetupIntegrationTest.setupAndConnectToH2Database:80 » JdbcSQLNonTransientConnection
[ERROR]   JulReconfigurationIntegrationTest.org.ops4j.pax.logging.it.JulReconfigurationIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1BuiltinAppendersIntegrationTest.org.ops4j.pax.logging.it.Log4J1BuiltinAppendersIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1FrameworkEventsIntegrationTest.org.ops4j.pax.logging.it.Log4J1FrameworkEventsIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1IntegrationTest.org.ops4j.pax.logging.it.Log4J1IntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1LocationInfoIntegrationTest.org.ops4j.pax.logging.it.Log4J1LocationInfoIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1MDCIntegrationTest.org.ops4j.pax.logging.it.Log4J1MDCIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1MarkersIntegrationTest.org.ops4j.pax.logging.it.Log4J1MarkersIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1MemoryIntegrationTest.org.ops4j.pax.logging.it.Log4J1MemoryIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1OsgiAppendersIntegrationTest.org.ops4j.pax.logging.it.Log4J1OsgiAppendersIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1OsgiErrorHandlersIntegrationTest.org.ops4j.pax.logging.it.Log4J1OsgiErrorHandlersIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1OsgiLayoutsIntegrationTest.org.ops4j.pax.logging.it.Log4J1OsgiLayoutsIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1R7AuditIntegrationTest.org.ops4j.pax.logging.it.Log4J1R7AuditIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1RefreshPaxLoggingApiIntegrationTest.org.ops4j.pax.logging.it.Log4J1RefreshPaxLoggingApiIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1RestartBothPaxLoggingBundlesIntegrationTest.org.ops4j.pax.logging.it.Log4J1RestartBothPaxLoggingBundlesIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1RestartPaxLoggingApiIntegrationTest.org.ops4j.pax.logging.it.Log4J1RestartPaxLoggingApiIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1RestartPaxLoggingServiceIntegrationTest.org.ops4j.pax.logging.it.Log4J1RestartPaxLoggingServiceIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1ThreadingIntegrationTest.org.ops4j.pax.logging.it.Log4J1ThreadingIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1UpdateJULLoggerLevelsIntegrationTest.org.ops4j.pax.logging.it.Log4J1UpdateJULLoggerLevelsIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1WithConfigAdminIntegrationTest.org.ops4j.pax.logging.it.Log4J1WithConfigAdminIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1WithDefaultConfigurationAndNoLog4jDebugIntegrationTest.org.ops4j.pax.logging.it.Log4J1WithDefaultConfigurationAndNoLog4jDebugIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1WithDefaultConfigurationIntegrationTest.org.ops4j.pax.logging.it.Log4J1WithDefaultConfigurationIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1WithoutConfigAdminIntegrationTest.org.ops4j.pax.logging.it.Log4J1WithoutConfigAdminIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1WithoutConfigAdminWithExternalPaxLoggingConfigurationIntegrationTest.org.ops4j.pax.logging.it.Log4J1WithoutConfigAdminWithExternalPaxLoggingConfigurationIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J1WithoutEventAdminIntegrationTest.org.ops4j.pax.logging.it.Log4J1WithoutEventAdminIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2BuiltinAppendersIntegrationTest.org.ops4j.pax.logging.it.Log4J2BuiltinAppendersIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2FrameworkEventsIntegrationTest.org.ops4j.pax.logging.it.Log4J2FrameworkEventsIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2IntegrationTest.org.ops4j.pax.logging.it.Log4J2IntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2JacksonLayoutIntegrationTest.org.ops4j.pax.logging.it.Log4J2JacksonLayoutIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2JdbcAppenderIntegrationTest.org.ops4j.pax.logging.it.Log4J2JdbcAppenderIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2JdbcLazyAppenderIntegrationTest.org.ops4j.pax.logging.it.Log4J2JdbcLazyAppenderIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2JdbcLazyJNDIAppenderIntegrationTest.org.ops4j.pax.logging.it.Log4J2JdbcLazyJNDIAppenderIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2LocationInfoIntegrationTest.org.ops4j.pax.logging.it.Log4J2LocationInfoIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2MDCIntegrationTest.org.ops4j.pax.logging.it.Log4J2MDCIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2MarkersIntegrationTest.org.ops4j.pax.logging.it.Log4J2MarkersIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2MemoryIntegrationTest.org.ops4j.pax.logging.it.Log4J2MemoryIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2MessagesIntegrationTest.org.ops4j.pax.logging.it.Log4J2MessagesIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2MetaIntegrationTest.org.ops4j.pax.logging.it.Log4J2MetaIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2MetaNoLog4j2DebugIntegrationTest.org.ops4j.pax.logging.it.Log4J2MetaNoLog4j2DebugIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2OsgiAppendersIntegrationTest.org.ops4j.pax.logging.it.Log4J2OsgiAppendersIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2R7AuditIntegrationTest.org.ops4j.pax.logging.it.Log4J2R7AuditIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2RefreshPaxLoggingApiIntegrationTest.org.ops4j.pax.logging.it.Log4J2RefreshPaxLoggingApiIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2RestartBothPaxLoggingBundlesIntegrationTest.org.ops4j.pax.logging.it.Log4J2RestartBothPaxLoggingBundlesIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2RestartPaxLoggingApiIntegrationTest.org.ops4j.pax.logging.it.Log4J2RestartPaxLoggingApiIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2RestartPaxLoggingLog4J2ServiceIntegrationTest.org.ops4j.pax.logging.it.Log4J2RestartPaxLoggingLog4J2ServiceIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2ThreadingIntegrationTest.org.ops4j.pax.logging.it.Log4J2ThreadingIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2UpdateJULLoggerLevelsIntegrationTest.org.ops4j.pax.logging.it.Log4J2UpdateJULLoggerLevelsIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2WithConfigAdminIntegrationTest.org.ops4j.pax.logging.it.Log4J2WithConfigAdminIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2WithDefaultConfigurationAndNoLog4j2DebugIntegrationTest.org.ops4j.pax.logging.it.Log4J2WithDefaultConfigurationAndNoLog4j2DebugIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2WithDefaultConfigurationIntegrationTest.org.ops4j.pax.logging.it.Log4J2WithDefaultConfigurationIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2WithoutConfigAdminIntegrationTest.org.ops4j.pax.logging.it.Log4J2WithoutConfigAdminIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2WithoutConfigAdminWithExternalLog4J2ConfigurationIntegrationTest.org.ops4j.pax.logging.it.Log4J2WithoutConfigAdminWithExternalLog4J2ConfigurationIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2WithoutConfigAdminWithExternalPaxLoggingConfigurationIntegrationTest.org.ops4j.pax.logging.it.Log4J2WithoutConfigAdminWithExternalPaxLoggingConfigurationIntegrationTest » ExceptionInInitializer
[ERROR]   Log4J2WithoutEventAdminIntegrationTest.org.ops4j.pax.logging.it.Log4J2WithoutEventAdminIntegrationTest » ExceptionInInitializer
[ERROR]   LogReaderIntegrationTest.org.ops4j.pax.logging.it.LogReaderIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackBuiltinAppendersIntegrationTest.org.ops4j.pax.logging.it.LogbackBuiltinAppendersIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackFrameworkEventsIntegrationTest.org.ops4j.pax.logging.it.LogbackFrameworkEventsIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackIntegrationTest.org.ops4j.pax.logging.it.LogbackIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackJacksonLayoutIntegrationTest.org.ops4j.pax.logging.it.LogbackJacksonLayoutIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackLocationInfoIntegrationTest.org.ops4j.pax.logging.it.LogbackLocationInfoIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackMDCIntegrationTest.org.ops4j.pax.logging.it.LogbackMDCIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackMarkersIntegrationTest.org.ops4j.pax.logging.it.LogbackMarkersIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackMemoryIntegrationTest.org.ops4j.pax.logging.it.LogbackMemoryIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackOsgiAppendersIntegrationTest.org.ops4j.pax.logging.it.LogbackOsgiAppendersIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackR7AuditIntegrationTest.org.ops4j.pax.logging.it.LogbackR7AuditIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackRefreshPaxLoggingApiIntegrationTest.org.ops4j.pax.logging.it.LogbackRefreshPaxLoggingApiIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackRestartBothPaxLoggingBundlesIntegrationTest.org.ops4j.pax.logging.it.LogbackRestartBothPaxLoggingBundlesIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackRestartPaxLoggingApiIntegrationTest.org.ops4j.pax.logging.it.LogbackRestartPaxLoggingApiIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackRestartPaxLoggingLogbackIntegrationTest.org.ops4j.pax.logging.it.LogbackRestartPaxLoggingLogbackIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackThreadingIntegrationTest.org.ops4j.pax.logging.it.LogbackThreadingIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackUpdateJULLoggerLevelsIntegrationTest.org.ops4j.pax.logging.it.LogbackUpdateJULLoggerLevelsIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackWithConfigAdminIntegrationTest.org.ops4j.pax.logging.it.LogbackWithConfigAdminIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackWithDefaultConfigurationAndNoLogbackDebugIntegrationTest.org.ops4j.pax.logging.it.LogbackWithDefaultConfigurationAndNoLogbackDebugIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackWithDefaultConfigurationIntegrationTest.org.ops4j.pax.logging.it.LogbackWithDefaultConfigurationIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackWithoutConfigAdminIntegrationTest.org.ops4j.pax.logging.it.LogbackWithoutConfigAdminIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackWithoutConfigAdminWithExternalLogbackConfigurationIntegrationTest.org.ops4j.pax.logging.it.LogbackWithoutConfigAdminWithExternalLogbackConfigurationIntegrationTest » ExceptionInInitializer
[ERROR]   LogbackWithoutEventAdminIntegrationTest.org.ops4j.pax.logging.it.LogbackWithoutEventAdminIntegrationTest » ExceptionInInitializer
[ERROR]   SimplestPaxLoggingServiceIntegrationTest.org.ops4j.pax.logging.it.SimplestPaxLoggingServiceIntegrationTest » ExceptionInInitializer
[INFO] 
[ERROR] Tests run: 84, Failures: 0, Errors: 84, Skipped: 0
```

**Comment by grgrzybek** [comment]
Looks like for JDK17 we need newer Felix. Thanks for report!

**Comment by oliverlietz** [comment]
When upgrading to Felix 7.0.3 and Karaf 4.3.5 my local build hangs in `Running org.ops4j.pax.logging.it.AllLoggingFacadesIntegrationTest` – are you on it?

**Comment by jbonofre** [comment]
Yes I know, I just mention that I upgraded to Felix 7.0.3 in Karaf 4.4.x and it works fine with JDK17+ (including pax exam).

**Comment by grgrzybek** [comment]
The reason of hanged test (Felix 7.0.3) is:
```
org.osgi.framework.BundleException: Activator stop error in bundle org.apache.felix.framework [0].
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2878)
	at org.apache.felix.framework.Felix.init(Felix.java:969)
	at org.apache.felix.framework.Felix.init(Felix.java:648)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:192)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:457)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.NullPointerException: Cannot invoke "org.osgi.framework.ServiceRegistration.unregister()" because "this.m_reg" is null
	at org.apache.felix.framework.Felix$SystemBundleActivator.stop(Felix.java:5284)
	at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:871)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2822)
	... 16 more
```

**Comment by grgrzybek** [comment]
Previous reason:
```
java.lang.RuntimeException: Unable to start system bundle.
	at org.apache.felix.framework.Felix.init(Felix.java:905)
	at org.apache.felix.framework.Felix.init(Felix.java:648)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:192)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:457)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by grgrzybek** [comment]
And the ultimate reason:
```
java.lang.NoSuchMethodError: 'java.util.Dictionary org.osgi.framework.FrameworkUtil.asDictionary(java.util.Map)'
	at org.apache.felix.framework.Felix$SystemBundleActivator.start(Felix.java:5166)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix.init(Felix.java:899)
	at org.apache.felix.framework.Felix.init(Felix.java:648)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:192)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:457)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

`FrameworkUtil` class is loaded from osgi.core-7.0.0 - should be 8.0.0 I guess.

**Comment by grgrzybek** [comment]
The guess was correct - I've removed:
```
<dependency>
    <groupId>org.osgi</groupId>
    <artifactId>osgi.core</artifactId>
    <scope>test</scope>
</dependency>
```

from pax-logging-it and it started to work.

**Comment by grgrzybek** [comment]
I had to upgrade from Karaf 4.2 to 4.3, but I think it's ok in 2022.
