### ISSUE TITLE
Support JPMS - do not include wrong META-INF/versions/9/module-info.class in pax-logging-api

### ISSUE THREAD

**Issue by oliverlietz** [ops4j/org.ops4j.pax.logging#440]
- Add required module information to support JPMS

**Comment by oliverlietz** [comment]
Work in progress in [branch jpms](https://github.com/ops4j/org.ops4j.pax.logging/tree/jpms)

**Comment by oliverlietz** [comment]
Issue related in slf4j: https://jira.qos.ch/browse/SLF4J-534

**Comment by oliverlietz** [comment]
Initializing of Log4j 2 fails even with several _opened_ packages:
```
ERROR: Bundle org.ops4j.pax.logging.pax-logging-api [32] Error starting atomos:application:file:///[...]/pax-logging-api-2.0.15-SNAPSHOT.jar (org.osgi.framework.BundleException: Activator start error in bundle org.ops4j.pax.logging.pax-logging-api [32].)
java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.util.PropertiesUtil
	at ModuleConnectLoader-org.ops4j.pax.logging.api/org.ops4j.pax.logging.api@2.0.15.SNAPSHOT/org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:82)
	at ModuleConnectLoader-org.ops4j.pax.logging.api/org.ops4j.pax.logging.api@2.0.15.SNAPSHOT/org.apache.logging.log4j.LogManager.<clinit>
(LogManager.java:61)
	at ModuleConnectLoader-org.ops4j.pax.logging.api/org.ops4j.pax.logging.api@2.0.15.SNAPSHOT/org.ops4j.pax.logging.internal.Activator.start(Activator.java:142)
	at org.apache.felix.framework@7.0.3/org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework@7.0.3/org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
	at org.apache.felix.framework@7.0.3/org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
	at org.apache.felix.framework@7.0.3/org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
	at org.apache.felix.framework@7.0.3/org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by grgrzybek** [comment]
Instead of making pax-logging bundles real JPMS modules (which is strange given the OSGi nature of these bundles), I think we should start with better repackaging of `org.apache.logging.log4j:log4j-core` dependency to not include `META-INF/versions/9/module-info.class`

**Comment by grgrzybek** [comment]
@oliverlietz I can't even imagine having Pax Logging as proper (set of) JPMS modules... For now let me just release a version which is at least not JPMS unfriendly (I'm removing log4j2's module-info).
