### ISSUE TITLE
Runtime exceptions are not notified via pax logging event topic

### ISSUE THREAD

**Issue by Nirothipan** [ops4j/org.ops4j.pax.logging#48]
When a runtime exception occurs, it is not notified via event topic listener and configurations are notified to be completed.

```
osgi> org.ops4j.pax.logging.pax-logging-api [log4j2] WARN : Error while converting string [OFFa] to type [class org.apache.logging.log4j.Level]. Using default value [null]. Ignored FQCN: org.apache.logging.log4j.spi.AbstractLogger
java.lang.IllegalArgumentException: Unknown level constant [OFFA].
	at org.apache.logging.log4j.Level.valueOf(Level.java:320)
	at org.apache.logging.log4j.core.config.plugins.convert.TypeConverters$LevelConverter.convert(TypeConverters.java:288)
	at org.apache.logging.log4j.core.config.plugins.convert.TypeConverters$LevelConverter.convert(TypeConverters.java:284)
	at org.apache.logging.log4j.core.config.plugins.convert.TypeConverters.convert(TypeConverters.java:419)
	at org.apache.logging.log4j.core.config.plugins.visitors.AbstractPluginVisitor.convert(AbstractPluginVisitor.java:149)
	at org.apache.logging.log4j.core.config.plugins.visitors.PluginAttributeVisitor.visit(PluginAttributeVisitor.java:45)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.generateParameters(PluginBuilder.java:258)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:135)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:548)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl.configureLog4J2(PaxLoggingServiceImpl.java:427)
	at org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl.updated(PaxLoggingServiceImpl.java:269)
	at org.ops4j.pax.logging.log4j2.internal.PaxLoggingServiceImpl$1ManagedPaxLoggingService.updated(PaxLoggingServiceImpl.java:569)
	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:279)
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:40)
```

**Comment by Nirothipan** [comment]
It seems the exceptions thrown in https://github.com/Nirothipan/org.ops4j.pax.logging/blob/logging-1.11.1/pax-logging-log4j2/src/main/java/org/ops4j/pax/logging/log4j2/internal/PaxLoggingServiceImpl.java#L427 is happening in another thread.

**Comment by grgrzybek** [comment]
`OFFA`? shouldn't it be `OFF`? Do you have `org.ops4j.pax.logging` PID configuration to show?

**Comment by Nirothipan** [comment]
Yes  , it works when I give correct configs. when I edit them incorrectly only  ( in this case OFFA ) it doesn't catch the exceptions.

**Comment by grgrzybek** [comment]
Hmm. The exception should be sent via EventAdmin using `org.ops4j.pax.logging.spi.support.EventAdminConfigurationNotifier#configurationError()` method - unless EventAdmin is not available. In all cases, the ERROR should be printed via logging backend's native "status logger" (and you see it in OSGi shell). Could you send me some configuration where I can see that it's **not** propagated?

**Comment by grgrzybek** [comment]
Please reopen if it's still a problem for you.
