### ISSUE TITLE
When start karaf ,show some error

### ISSUE THREAD

**Issue by penetest** [ops4j/org.ops4j.pax.logging#50]
some error infos:
```
[org.ops4j.pax.url.commons.handler.HandlerActivator] : Handler for protocols [wrap] started
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling JULI Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Enabling Log4J v2 API support. Ignored FQCN: org.apache.logging.log4j.spi.A
bstractLogger*ERROR* Worker thread CM Configuration Updater did not terminate within 5 seconds; trying to kill
*ERROR* [org.osgi.service.log.LogService, org.knopflerfish.service.log.LogService, org.ops4j.pax.logging.PaxLoggingService, org.osgi.service.cm.ManagedServic
e, id=9, unregistered]: Unexpected problem updating configuration org.ops4j.pax.loggingjava.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:853)
	at org.apache.felix.cm.impl.UpdateThread.terminate(UpdateThread.java:197)
	at org.apache.felix.cm.impl.ConfigurationManager.stop(ConfigurationManager.java:224)
	at org.apache.felix.cm.impl.persistence.PersistenceManagerTracker.deactivate(PersistenceManagerTracker.java:131)
	at org.apache.felix.cm.impl.persistence.PersistenceManagerTracker.stop(PersistenceManagerTracker.java:103)
	at org.apache.felix.cm.impl.Activator.stop(Activator.java:120)
	at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:719)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2636)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1391)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
*ERROR* Unexpected problem providing configuration org.ops4j.pax.logging to service [org.osgi.service.log.LogService, org.knopflerfish.service.log.LogService
, org.ops4j.pax.logging.PaxLoggingService, org.osgi.service.cm.ManagedService, id=9, unregistered]java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:511)
	at org.apache.felix.framework.BundleContextImpl.ungetService(BundleContextImpl.java:475)
	at org.apache.felix.cm.impl.helper.BaseTracker.ungetRealService(BaseTracker.java:213)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:161)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1113)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1069)
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105)
	at java.lang.Thread.run(Thread.java:748)
*ERROR* Unexpected problem providing configuration org.ops4j.pax.url.mvn to service [org.osgi.service.cm.ManagedService, id=5, bundle=2/mvn:org.ops4j.pax.url
/pax-url-aether/2.6.1]java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:511)
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:451)
	at org.apache.felix.cm.impl.helper.BaseTracker.getRealService(BaseTracker.java:207)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:102)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1113)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1069)
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105)
	at java.lang.Thread.run(Thread.java:748)
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling SLF4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Jakarta Commons Logging API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Log4J API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Avalon Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling JULI Logger API support.
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.logging.internal.Activator] : Disabling Log4J v2 API support. Ignored FQCN: org.apache.logging.log4j.spi.
AbstractLoggerorg.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.url.commons.handler.HandlerActivator] : Handler for protocols [wrap] stopped
org.ops4j.pax.logging.pax-logging-api[org.ops4j.pax.url.mvn.internal.Activator] : Handler for protocols mvn stopped
```

**Comment by grgrzybek** [comment]
Could you please share more information? Like Karaf's `etc/startup.properties` or a thread dump created before `Worker thread CM Configuration Updater did not terminate within 5 seconds` is printed?

**Comment by jbonofre** [comment]
Any update about this one ? If not soon, I will close this issue.

**Comment by grgrzybek** [comment]
I'm closing this one. From the stack trace it seems that CM is being stopped early in Framework lifecycle. If there are new hints, please reopen.
