### ISSUE TITLE
[2.2.x] Upgrade to Log4j2 2.24.1

### ISSUE THREAD

**Issue by ihrasko** [ops4j/org.ops4j.pax.logging#552]
We would like to get log4j2 version [2.24.0](https://github.com/apache/logging-log4j2/milestone/14?closed=1) to have fix for https://github.com/apache/logging-log4j2/issues/2380.

**Comment by grgrzybek** [comment]
Supersedes #550.

**Comment by grgrzybek** [comment]
But 2.24.0 is not there yet.

**Comment by grgrzybek** [comment]
But don't we fix it with #516 ?

**Comment by PeterSuna** [comment]
Hello, the [log4j 2.24.0](https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.24.0) was released two weeks ago. Could be this please integrated in next planned release?

In the last org.ops4j.pax.logging release 2.2.7, I encountered probably similar issue as described in apache/logging-log4j2#2380. If the following variables are processed:

**fqcn** = "org.ops4j.pax.logging.slf4j.Slf4jLogger"
**level** = DEBUG
**marker** = null
**message**="  javax.management.MBeanOperationInfo[description=interrupts a pool thread, name=interruptThread, returnType=boolean, signature=[javax.management.MBeanParameterInfo[description=, name=id, type=long, descriptor={}]], impact=unknown, descriptor={}]"
**t** =null
**m_delegate** = org.eclipse.jetty.jmx.MBeanContainer:DEBUG in pax-logging

[m_delegate.logMessage(fqcn, level, marker, msg, t)](https://github.com/ops4j/org.ops4j.pax.logging/blob/main/pax-logging-log4j2/src/main/java/org/ops4j/pax/logging/log4j2/internal/PaxLoggerImpl.java#L1129)

I got the following exception:
```
java.lang.IllegalArgumentException: found 2 argument placeholders, but provided 1 for pattern `  javax.management.MBeanOperationInfo[description=interrupts a pool thread, name=interruptThread, returnType=boolean, signature=[javax.management.MBeanParameterInfo[description=, name=id, type=long, descriptor={}]], impact=unknown, descriptor={}]`
	at org.apache.logging.log4j.message.ParameterFormatter.formatMessage(ParameterFormatter.java:233) ~[bundleFile:?]
	at org.apache.logging.log4j.message.ParameterizedMessage.formatTo(ParameterizedMessage.java:266) ~[bundleFile:?]
	at org.apache.logging.log4j.message.ParameterizedMessage.getFormattedMessage(ParameterizedMessage.java:253) ~[bundleFile:?]
	at org.apache.logging.log4j.core.filter.RegexFilter.filter(RegexFilter.java:89) ~[bundleFile:?]
	at org.apache.logging.log4j.core.filter.AbstractFilterable.isFiltered(AbstractFilterable.java:152) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.AppenderControl.isFilteredByAppender(AppenderControl.java:155) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:132) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:705) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:663) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:696) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:665) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:540) ~[bundleFile:?]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:67) ~[bundleFile:?]
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:155) ~[bundleFile:?]
	at org.ops4j.pax.logging.log4j2.internal.PaxLoggerImpl.doLog0(PaxLoggerImpl.java:1129) ~[bundleFile:?]
	at org.ops4j.pax.logging.log4j2.internal.PaxLoggerImpl.doLog(PaxLoggerImpl.java:1099) ~[bundleFile:?]
	at org.ops4j.pax.logging.log4j2.internal.PaxLoggerImpl.debug(PaxLoggerImpl.java:265) ~[bundleFile:?]
	at org.ops4j.pax.logging.internal.TrackingLogger.debug(TrackingLogger.java:172) ~[bundleFile:?]
	at org.ops4j.pax.logging.slf4j.Slf4jLogger.log(Slf4jLogger.java:1411) ~[bundleFile:?]
```

Thanks.

**Comment by grgrzybek** [comment]
Thanks - I'll try to find some time next week.
